deployment:
  tasks:
    - export DEPLOYPATH=/home/surestr2/public_html/
    # Create a backup of the current site
    - if [ -d $DEPLOYPATH ]; then mkdir -p ~/site_backups/$(date +%Y%m%d_%H%M%S); cp -R $DEPLOYPATH/* ~/site_backups/$(date +%Y%m%d_%H%M%S)/; fi
    # Clean existing deploy directory (except for some sensitive files)
    - find $DEPLOYPATH -mindepth 1 -not -path "$DEPLOYPATH/api*" -not -path "$DEPLOYPATH/.htaccess" -not -path "$DEPLOYPATH/.env*" -delete
    # Copy new files
    - /bin/cp -R dist/* $DEPLOYPATH
    # Copy .htaccess file explicitly
    - /bin/cp -f public/.htaccess $DEPLOYPATH/.htaccess
    # Ensure proper permissions
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
    # Set proper mime types for JavaScript files
    - find $DEPLOYPATH -type f -name "*.js" -exec chmod 644 {} \;
    - find $DEPLOYPATH -type f -name "*.js" -exec chattr +i {} \;
    # Ensure PHP files are executable
    - find $DEPLOYPATH -name "*.php" -type f -exec chmod 755 {} \;
    # Make sure the API directory has the right permissions
    - if [ -d "$DEPLOYPATH/api" ]; then chmod 755 $DEPLOYPATH/api; fi
    # Log deployment
    - echo "Deployment completed at $(date)" > $DEPLOYPATH/deploy_log.txt
